### ISSUE TITLE
Example .gitlab-ci.yml is not valid

### ISSUE THREAD

**Issue by jasondamour** [ElectroStar/Sonar-Scanner#1]
The example .gitlab-ci.yml cited in the readme is not valid and will not completely compile. the "except" block of the sonarqube_preview step is not valid. It seems to work if the except block is moved before the script, not sure why

**Comment by jasondamour** [comment]
update: this may be a bug with gitlab. It is valid according to their lint tool, but the sonarqube_preview job doesn't appear

**Comment by ElectroStar** [comment]
Thank you for your report. It seams to be a bug as you mentioned in your update. 
I will check it and finally add the two new versions of the Sonar CLI Scanner this weekend.

**Comment by ElectroStar** [comment]
Hey jdamour98.
First of all sorry for my late response. 
I couldn't find any bug for the combination of Gitlab CE 10.8.4 and Gitlab Runner 10.8.0.
Could you tell me the version numbers of your combination.
